### ISSUE TITLE
copr build invocation?

### ISSUE THREAD

**Issue by verdurin** [cmd-ntrf/copr_scripts#1]
With apologies for being nosy, what method are you using for the build itself on copr?
On the repo, it just says "custom build method".
So far, I've been using the rather unsatisfactory approach of building an SRPM locally and triggering the copr build with that.

**Comment by cmd-ntrf** [comment]
No need to apologize. To get the full picture, I recommend you fork the repo you want to know more about.

How-to
1. Sign-up / Login in COPR
2. Go to the repo you want to know more about : https://copr.fedorainfracloud.org/coprs/cmdntrf/Slurm19.05-nvml/
3. Click on the "packages" tab, then click on the package name leading to : https://copr.fedorainfracloud.org/coprs/cmdntrf/Slurm19.05-nvml/package/slurm/
4. Click on the "edit" button at the right of "Default Build Source" header.
5. In the "provide the source" section, you will see that I invoke the copr_scripts like this:
```
curl https://raw.githubusercontent.com/cmd-ntrf/copr_scripts/master/slurm19.05/slurm19.05.sh | bash
```

The script prepares the source in the format COPR is expecting.

The configuration of the build environment is done under the "Settings" tab -> Project details -> 2. Build options -> epel-7-x86_64 -> Edit.
